import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Notification from './components/Notification'
import { Footer, Navbar } from './components/layout'
import AuthSession from './components/AuthSession'
import { auth } from '@/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth()

  console.log('root', session)

  return (
    <AuthSession>
      <html lang='en'>
        <body className={`${inter.className} bg-gray-100`}>
          <Navbar />
          {children}
          <Notification />
          <Footer />
        </body>
      </html>
    </AuthSession>
  )
}
